arb-dir: lib/src/core/locale/l10n
template-arb-file: app_en.arb
output-dir: lib/src/core/locale/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
preferred-supported-locales:
  - en
  - mr
  - hi